name: matrix
on: push
jobs: 
  node-version:
    runs-on: ubuntu-latest
    steps:
      - name: Log node node version
        run: node -v
      - uses: actions/steup-node@v1
        with: 
          node-version: 6
      - name: Log node version (2)
        run: node -v
